require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SuppliresController do

  # This should return the minimal set of attributes required to create a valid
  # Supplire. As you add validations to Supplire, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SuppliresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all supplires as @supplires" do
      supplire = Supplire.create! valid_attributes
      get :index, {}, valid_session
      assigns(:supplires).should eq([supplire])
    end
  end

  describe "GET show" do
    it "assigns the requested supplire as @supplire" do
      supplire = Supplire.create! valid_attributes
      get :show, {:id => supplire.to_param}, valid_session
      assigns(:supplire).should eq(supplire)
    end
  end

  describe "GET new" do
    it "assigns a new supplire as @supplire" do
      get :new, {}, valid_session
      assigns(:supplire).should be_a_new(Supplire)
    end
  end

  describe "GET edit" do
    it "assigns the requested supplire as @supplire" do
      supplire = Supplire.create! valid_attributes
      get :edit, {:id => supplire.to_param}, valid_session
      assigns(:supplire).should eq(supplire)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Supplire" do
        expect {
          post :create, {:supplire => valid_attributes}, valid_session
        }.to change(Supplire, :count).by(1)
      end

      it "assigns a newly created supplire as @supplire" do
        post :create, {:supplire => valid_attributes}, valid_session
        assigns(:supplire).should be_a(Supplire)
        assigns(:supplire).should be_persisted
      end

      it "redirects to the created supplire" do
        post :create, {:supplire => valid_attributes}, valid_session
        response.should redirect_to(Supplire.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supplire as @supplire" do
        # Trigger the behavior that occurs when invalid params are submitted
        Supplire.any_instance.stub(:save).and_return(false)
        post :create, {:supplire => { "code" => "invalid value" }}, valid_session
        assigns(:supplire).should be_a_new(Supplire)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Supplire.any_instance.stub(:save).and_return(false)
        post :create, {:supplire => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested supplire" do
        supplire = Supplire.create! valid_attributes
        # Assuming there are no other supplires in the database, this
        # specifies that the Supplire created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Supplire.any_instance.should_receive(:update).with({ "code" => "MyString" })
        put :update, {:id => supplire.to_param, :supplire => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested supplire as @supplire" do
        supplire = Supplire.create! valid_attributes
        put :update, {:id => supplire.to_param, :supplire => valid_attributes}, valid_session
        assigns(:supplire).should eq(supplire)
      end

      it "redirects to the supplire" do
        supplire = Supplire.create! valid_attributes
        put :update, {:id => supplire.to_param, :supplire => valid_attributes}, valid_session
        response.should redirect_to(supplire)
      end
    end

    describe "with invalid params" do
      it "assigns the supplire as @supplire" do
        supplire = Supplire.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Supplire.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplire.to_param, :supplire => { "code" => "invalid value" }}, valid_session
        assigns(:supplire).should eq(supplire)
      end

      it "re-renders the 'edit' template" do
        supplire = Supplire.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Supplire.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplire.to_param, :supplire => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supplire" do
      supplire = Supplire.create! valid_attributes
      expect {
        delete :destroy, {:id => supplire.to_param}, valid_session
      }.to change(Supplire, :count).by(-1)
    end

    it "redirects to the supplires list" do
      supplire = Supplire.create! valid_attributes
      delete :destroy, {:id => supplire.to_param}, valid_session
      response.should redirect_to(supplires_url)
    end
  end

end
